#!/bin/bash
#
# Debian installation script :: postinst
#

# create a symbolic link to builder script
ln -s /usr/local/lib/udoo-arduino-cli/tools/udoo-arduino-build /usr/local/bin/udoo-arduino-build

exit 0;
